# get http://localhost:8000/customers/5

# get http://localhost:8000/orders

# get http://localhost:8000/orders/total-sale

# get http://localhost:8000/orders/4

post http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json

{
     "customerId" : 2,
     "employeeId" : 2, 
     "items" : [
         {
          "productId": 3,
          "amount": 10,
          "discount": 0
         },
        {
          "productId": 3,
          "amount": 10,
          "discount": 0
         }
     ]
}


        